baseURL = 'https://shtlrs.com/'
languageCode = 'en-us'
title = 'Amrou Bellalouna'
theme = "hugotex"
enableRobotsTXT = true

[params]
customCSS = ["css/styles.css"]
lightmode = true
opengraph = true
description = "Software Engineering blog by Amrou Bellalouna. Insights on solving day to day engineering problems."

[params.Author]
Name = "Amrou Bellalouna"

[social]
github = "shtlrs"

[[menus.main]]
name = "Blog"
pageRef = "/posts"
weight = 10

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 20


[caches]
  [caches.images]
    dir = ':cacheDir/images'
