baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Amrou Bellalouna'
theme = "hugotex"
#ignoreLogs = ['warning-goldmark-raw-html']

[params]
customCSS = ["css/styles.css"]
lightmode = true
