baseURL = 'https://shtlrs.com/'
languageCode = 'en-us'
title = 'Amrou Bellalouna'
theme = "hugotex"
#ignoreLogs = ['warning-goldmark-raw-html']

[params]
customCSS = ["css/styles.css"]
lightmode = true

[[menus.main]]
name = "Blog"
pageRef = "/posts"
weight = 10

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 20


[caches]
  [caches.images]
    dir = ':cacheDir/images'