baseURL = 'https://shtlrs.github.io/'
languageCode = 'en-us'
title = 'Amrou Bellalouna'
theme = "hugotex"
#ignoreLogs = ['warning-goldmark-raw-html']

[params]
customCSS = ["css/styles.css"]
lightmode = true


[caches]
  [caches.images]
    dir = ':cacheDir/images'